---
layout: post
date: 2021-01-10 18:13:00
title: "9주차 과제: 예외 처리."
description: "study halle"
subject: live study
category: [ java study halle ]
tags: [ java, exception, error ]
use_math: true
comments: true
---

> 해당 글을 [백기선 님의 자바 스터디 9주차 과제](https://github.com/whiteship/live-study/issues/9)를 공부하고 공유하기 위해서 작성되었습니다.

# 목표

자바의 예외 처리에 대해 학습한다.

# 학습할 것

+ [자바에서 예외 처리 방법](#자바에서-예외-처리-방법)
+ [자바가 제공하는 예외 계층 구조](#자바가-제공하는-예외-계층-구조)
+ [Exception과 Error의 차이는?](#exception과-error의-차이는)
+ [RuntimeException과 RE가 아닌 것의 차이는?](#runtimeexception과-re가-아닌-것의-차이는)
+ [커스텀한 예외 만드는 방법](#커스텀한-예외-만드는-방법)

# 자바에서 예외 처리 방법

&nbsp;&nbsp;&nbsp;프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우가 있다. 이러한 결과를 초래하는 원인을 프로그램 에러 또는 오류라고 한다.

&nbsp;&nbsp;&nbsp;이를 발생시점에 따라 <b>컴파일 에러(compile-time error)</b>와 <b>런타임 에러(runtime error)</b>로 나눌 수 있다.  
컴파일 에러는 컴파일 할 때 발생하는 에러를 말하고 런타임 에러는 프로그램의 실행도중에 발생하는 에러를 말한다. 이 외에 <b>논리적 에러(logical error)</b>가 있는데, 컴파일도 잘되고 실행도 잘되지만 의도한 것과 다르게 동작하는 것을 말한다.

+ <b>컴파일 에러</b> 컴파일 시에 발생하는 에러
+ <b>런타임 에러</b> 실행 시에 발생하는 에러
+ <b>논리적 에러</b> 실행은 되지만, 의도와 다르게 동작하는 것

기본적으로 소스코드를 컴파일 하면 컴파일러가 소스코드(*.java)에 대해 오타나 잘못된 구문, 자료형 체크등의 기본적인 검사를 수행하여 오류가 있는지 알려준다. 컴파일러가 알려준 에러들을 모두 수정해서 컴파일을 성공적으로 마치고 나면, 클래스 파일(\*.class)이 생성되고, 생성된 클래스 파일을 실행할 수 있게 되는 것이다.

&nbsp;&nbsp;&nbsp;하지만 컴파일이 에러없이 성공적으로 마쳤다고 해서 실행 시 에러가 발생하지 않는다는 보장은 없다. 컴파일러가 소스코드의 기본적인 사항은 컴파일 시에 모두 걸러 줄 수 있지만, 실행 중에 발생할 수 있는 잠재적인 오류까지 검사할 수 없기 때문이다.

## 예외 처리(exception handling)

&nbsp;&nbsp;&nbsp;예외 처리(exception handling)란, 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이다. 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것이다.

+ <b>예외처리(exception handling)</b>의
  + <b>정의</b> - 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
  + <b>목적</b> - 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것

발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외(uncaught exception)는 JVM의 <b>예외처리기(UncaughtExceptionHandler)</b>가 받아서 예외의 원인을 출력한다.

## try-catch문

&nbsp;&nbsp;&nbsp;예외를 처리하기 위해서는 `try-catch`문을 사용하며, 구조는 다음과 같다.

```java
    try {
        // 예외가 발생할 가능성이 있는 문장들
    } catch (Exception1 e1) {
        // Exception1이 발생햇을 경우, 이를 처리하는 문장
    } catch (Exception2 e2) {
        // Exception2가 발생햇을 경우, 이를 처리하는 문장
    } catch (Exception3 e3) {
        // Exception3이 발생했을 경우, 이를 처리하는 문장
    }
```

하나의 `try`블럭 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 `catch`블럭이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한 개의 `catch`블럭만 수행된다.

```java
    class App {
        public static void main(String[] args) {
            try {
                try { } catch (Exception e) { }
            } catch (Exception e) {
                try { } catch (Exception e) { } // 에러. 변수 e가 중복.
            } // try-catch 끝

            try {

            } catch (Exception e) {

            } // try-catch 끝
        }
    }
```

이 예제는 아무 일도 발생하지 않는다. 예제에서 알 수 있듯이 하나의 메서드 내에 여러 개의 `try-catch`문이 사용될 수 있으며, try블럭 또는 catch블럭에 또 다른 try-catch문이 포함될 수 있다.  
catch블럭의 괄호 내에 선언된 변수는 catch블럭 내에서만 유효하기 때문에 위의 모든 catch블럭에 참조변수 `e` 하나 만을 사용해도 된다.

&nbsp;&nbsp;&nbsp;그러나 catch블럭 내에 또 하나의 try-catch문이 포함된 경우, 같은 이름의 참조변수를 사용해서는 안 된다. 각 catch블럭에 선언된 두 참조변수의 영역이 서로 겹치므로 다른 이름을 사용해야만 서로 구별되기 때문이다.

## try-catch문에서의 흐름

&nbsp;&nbsp;&nbsp;try-catch문에서, 예외가 발생한 경우와 발생하지 않았을 때의 흐름이 달라진다.

&#9654;<b>try블럭 내에서 예외가 발생하지 않은 경우,</b>
1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.

```java
class App {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(4);
        } catch (Exception e) {
            System.out.println(5);
        }
        System.out.println(6);
    }
}
```

<img src="/assets/img/study/trycatch01.png" width="70%" align="center"><br/>

&#9654;<b>try블럭 내에서 예외가 발생한 경우,</b>
1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.

```java
class App {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0); // 고의로 ArithmeticException을 발생
            System.out.println(4);
        } catch (Exception e) {
            System.out.println(5);
        }
        System.out.println(6);
    }
}
```

<img src="/assets/img/study/trycatch02.png" width="70%" align="center"><br/>

이처럼 try블럭에서 예외가 발생하면, 예외가 발생한 위치 이후에 있는 try블럭의 문장들은 수행되지 않으므로, try블럭에 포함시킬 코드의 범위를 잘 선택해야한다.

## catch블럭

&nbsp;&nbsp;&nbsp;catch블럭은 괄호( )와 블럭{ } 두 부분으로 나눠져 있는데, 괄호 내에는 처리하고자 하는 예외와 같은 타입의 참조변수 하나를 선언해야한다.

&nbsp;&nbsp;&nbsp;예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어진다. 예를 들어 `ArithmeticException`이 발생했다면 `ArithmeticException`인스턴스가 생성된다. 예외가 발생한 문장이 try블럭에 포함되어 있다면, 이 예외를 처리할 수 있는 catch블럭이 있는지 찾게된다.

첫 번째 catch블럭부터 차례로 내려가면서 catch블럭의 괄호 내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof연산자를 이용해서 검사하게 되는데, 검사결과가 true인 catch블럭을 만날 때까지 검사는 계속된다.  
검사결과가 true인 catch블럭을 찾게 되면 블럭에 있는 문장들을 모두 수행한 후에 try-catch문을 빠져나가고 예외는 처리되지만, 검사결과가 true인 catch블럭이 하나도 없으면 예외는 처리되지 않는다.

&nbsp;&nbsp;&nbsp;모든 예외 클래스는 Exception클래스의 자손이므로, catch블럭의 괄호에 Exception클래스 타입의 참조변수를 선언해 놓으면 어떤 종류의 예외가 발생하더라도 이 catch블럭에 의해서 처리된다.

```java
class App {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);
            System.out.println(4);
        } catch (ArithmeticException ae) {
            if(ae instanceof ArithmeticException)
              System.out.println("true");
            System.out.println("ArithmeticException");
        } catch (Exception e) {
            System.out.println("Exception");
        }
        System.out.println(6);
    }
}
```

<img src="/assets/img/study/catchblock.png" width="70%" align="center"><br/>

try블럭에서 ArithmeticException이 발생하였으므로 catch블럭을 하나씩 차례로 검사하게 되는데, 첫 번째 검사에서 일치하는 catch블럭을 찾았기 때문에 두 번째 catch블럭은 검사하지 않았다. 만일 ArithmeticException이 아닌 다른 종류의 에러가 발생한 경우에는 두 번째 catch블럭인 Exception클래스 타입의 참조변수를 선언한 곳에서 처리되었을 것이다.

## printStackTrace()와 getMessage()



# 자바가 제공하는 예외 계층 구조

자바에서는 실행 시 발생할 수 있는 오류(Exception과 Error)를 클래스로 정의하였다. Exception과 Error 또한 클래스이므로 Object 클래스의 자손이다.

<img>

모든 예외의 최고 조상은 <b>Exception클래스</b>이며, 상속계층도를 Exception클래스부터 도식화하면 다음과 같다.

<img>

# Exception과 Error의 차이는?

&nbsp;&nbsp;&nbsp;자바에서는 실행 시(runtime) 발생할 수 있는 프로그램 오류를 <b>에러(Error)</b>와 <b>예외(Exception)</b>, 두 가지로 구분한다.

### 에러 Error

에러는 메모리 부족(OutOfMemoryError)이나 스택오버플로우(StackOverflowError)와 같은 발생하게 되면 복구할 수 없는 심각한 수준의 오류를 뜻한다. 시스템에 비정상적인 상황이 생겼을 때 발생하므로 System level의 문제이다.

### 예외 Exception

예외는 개발자가 작성한 로직 내에서 발생한 오류를 뜻한다. 따라서 발생하더라도 개발자가 이에 대한 적절한 코드를 미리 작성해 놓음으로써 프로그램의 비정상적인 종료와 같은 오류를 방지할 수 있다.

+ <b>에러(error)</b> 프로그램 코드에 의해서 수습될 수 <b>없는</b> 심각한 오류
+ <b>예외(exception)</b> 프로그램 코드에 의해서 수습될 수 <b>있는</b> 상대적으로 미약한 오류

### Exception과 Error는 System Level의 문제와 Application Level의 문제의 차이이다.

# RuntimeException과 RE가 아닌 것의 차이는?

상속계층도에서 볼 수 있듯이 예외 클래스는 두 그룹으로 나눌 수 있다.

+ Exception클래스와 그 자손들
+ RuntimeException클래스와 그 자손들

### Unchecked Exception

Unchecked Exception(RuntimeException클래스와 그 자손들)은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다.  

예를 들어

+ 배열의 범위를 벗어난다던가(ArrayIndexOutOfBoundsException)
+ 값이 null인 참조변수의 멤버를 호출하려 했다던가(NullPointerException)
+ 클래스 간의 형변환을 잘못했다던가(ClassCastException)
+ 정수를 0으로 나누려고(ArithmeticException)

하는 경우에 발생한다.

명시적인 처리를 강제하지 않고, 실행되는 시점(Runtime)에 확인한다.

### Checked Exception

Checked Exception(RE클래스들을 제외한 나머지 클래스들)은 주로 외부의 영향으로 발생하는 것들로, 프로그램 사용자들의 동작에 의해서 발생하는 경우가 많다.

예를 들어

+ 존재하지 않는 파일의 이름을 입력했다던가(FileNotFoundException)
+ 실수로 클래스의 이름을 잘못 적었다던가(ClassNotFoundException)
+ 입력한 데이터 형식이 잘못된(DataFormatException)

경우에 발생한다.

이름에서 알 수 있듯이 반드시 예외를 처리해야하고, 컴파일되는 시점에 확인한다.

## 어떻게 구분 할 수 있을까?

&nbsp;&nbsp;&nbsp;두 가지의 가장 명확한 구분 기준은 <b>꼭 처리를 해야 하는냐</b>이다. Checked Exception이 발생할 가능성이 있는 메소드라면 반드시 `try ~ catch`로 감싸거나 `throw`로 던져서 처리해야 한다.

반면에 Unchecked Exception은 명시적인 예외처리를 하지 않아도 된다. 대부분의 예외가 부주의로 발생하고, 예측하지 못했던 상황의 예외가 아니기 때문에 굳이 로직으로 처리 할 필요가 없도록 만들어져 있다.

&nbsp;&nbsp;&nbsp;예외를 확인할 수 있는 시점으로도 구분할 수 있다. 일반적으로 컴파일 단계에서 명확하게 Exception 체크가 가능한 것을 Checked Exception이라 하며, 실행과정 중 어떠한 특정 논리에 의해 발견되는 Exception을 Unchecked Exception이라 한다.

# 커스텀한 예외 만드는 방법

---
**Reference**
+ [자바의 정석 3/e](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788994492032)
+ [Java in a Nutshell](https://www.amazon.com/Java-Nutshell-Desktop-Quick-Reference/dp/1492037257/ref=sr_1_1?dchild=1&keywords=Java+in+a+Nutshell&qid=1605393888&s=books&sr=1-1)
+ [오라클 공식 가이드](https://docs.oracle.com/javase/tutorial/java/TOC.html)
+ <https://www.nextree.co.kr/p3239/>
